language: node_js
node_js:
  - '7'
notifications:
  email: false

install:
  - npm install -g ionic cordova
  - npm install

script:
  - ionic build browser

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: $CF_USER
  password: $CF_PASSWORD
  api: $CF_API
  organization: sandbox
  space: TZHWEDA9
  on:
    branch: develop
